### ISSUE TITLE
Darkmode patch

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/addons-homeassistant#3]
AdminLTE offers built-in dark mode.

JavaScript function to toggle the dark-mode class on the body element.

```javascript
 function toggleDarkMode() {
     document.body.classList.toggle('dark-mode');
 }
```

Event Listener: Attach an event listener to the toggle button to call the toggleDarkMode function when clicked.

```javascript
document.getElementById('darkModeToggle').addEventListener('click', toggleDarkMode);
```

Remember User Preference: To persist the user's dark mode preference across sessions, you can use localStorage.

```javascript
function loadDarkMode() {
    let darkMode = JSON.parse(localStorage.getItem('darkMode'));
    if (darkMode) {
        document.body.classList.add('dark-mode');
    }
}

function toggleDarkMode() {
    document.body.classList.toggle('dark-mode');
    localStorage.setItem('darkMode', JSON.stringify(document.body.classList.contains('dark-mode')));
}

window.addEventListener('load', loadDarkMode);
```

```javascript

```

```javascript

```

**Comment by samrocketman** [comment]
Dark mode CSS.

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #343a40;
    color: #ffffff;
  }

  .main-header, .main-sidebar, .control-sidebar {
    background-color: #212529;
    color: #ffffff;
  }

  .content-wrapper {
    background-color: #495057;
  }

  /* Add more style overrides for other AdminLTE elements as needed */
  .card {
    background-color: #343a40;
    color: #ffffff;
  }
  .card-header {
      background-color: #212529;
      color: #ffffff;
  }
  a {
      color: #bb86fc;
  }
  a:hover {
      color: #3700b3;
  }
  /* Example for table elements */
  .table {
    color: #ffffff;
  }

  .table thead th {
    border-bottom-color: #6c757d;
    color: #ffffff;
  }

  .table-bordered, .table-bordered td, .table-bordered th {
    border-color: #6c757d;
  }

  .table-striped tbody tr:nth-of-type(odd) {
    background-color: rgba(255, 255, 255, 0.05);
  }
}
```
